name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # This tells GitHub to run this script ONLY when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub creates a temporary Linux server to run these tasks
    
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/Docker_learn
            
            # 1. Get the latest code from GitHub
            git pull origin main
            
            # 2. Build the new Docker image
            sudo docker build -t my-live-website .
            
            # 3. Kill the old container (the || true prevents errors if it doesn't exist yet)
            sudo docker rm -f production-web || true
            
            # 4. Start the new container
            sudo docker run -d -p 80:80 --name production-web my-live-website
