name: Test and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        
      - name: Validate HTML Syntax
        run: echo "Pretending to run an HTML Linter here... looks good!"
        
      - name: Test Docker Build
        run: docker build -t test-website-build .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/docker/Docker_learn
            git pull origin main
            sudo docker build -t my-live-website .
            sudo docker rm -f production-web || true
            sudo docker run -d -p 80:80 --name production-web my-live-website
